#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC2034
# This file is generated by `bash scripts/build-bootstrap.sh`.
# Do not edit it directly.

set -euo pipefail

# --- begin: scripts/lib/cli.sh ---
# shellcheck shell=bash
# shellcheck disable=SC2034

print_usage() {
  cat <<'EOF'
Uso:
  bash install.sh [opções]
  curl -fsSL https://obslove.dev | bash -s -- [opções]

Opções:
  -c, --check             Valida o runtime sem instalar apps; via curl, o bootstrap ainda pode sincronizar o clone e preparar dependências iniciais.
  -e, --exclusive-key     Destrutiva: remove as outras chaves SSH do GitHub e mantém só a atual.
  -n, --no-gh             Pula a etapa de GitHub SSH.
  -s, --ssh-name NOME     Define o nome da chave SSH enviada ao GitHub.
  -v, --verbose           Desativa o modo resumido e mostra a saída completa.
  -h, --help              Exibe esta ajuda.
EOF
}

parse_cli_args() {
  while (($# > 0)); do
    case "$1" in
      -c|--check)
        CHECK_ONLY=1
        shift
        ;;
      -e|--exclusive-key)
        EXCLUSIVE_GITHUB_SSH_KEY=1
        shift
        ;;
      -n|--no-gh)
        SKIP_GITHUB_SSH=1
        shift
        ;;
      -s|--ssh-name)
        [[ $# -ge 2 ]] || {
          printf 'Erro: faltou informar o valor de %s.\n' "$1" >&2
          exit 1
        }
        GITHUB_SSH_KEY_NAME="$2"
        shift 2
        ;;
      --ssh-name=*)
        GITHUB_SSH_KEY_NAME="${1#*=}"
        shift
        ;;
      -v|--verbose)
        STEP_OUTPUT_ONLY=0
        shift
        ;;
      -h|--help)
        print_usage
        exit 0
        ;;
      --)
        shift
        break
        ;;
      -*)
        printf 'Erro: opção desconhecida: %s\n' "$1" >&2
        printf 'Use --help para ver as opções disponíveis.\n' >&2
        exit 1
        ;;
      *)
        printf 'Erro: argumento não reconhecido: %s\n' "$1" >&2
        exit 1
        ;;
    esac
  done

  if (($# > 0)); then
    printf 'Erro: argumentos extras não reconhecidos: %s\n' "$*" >&2
    exit 1
  fi
}
# --- end: scripts/lib/cli.sh ---

# --- begin: scripts/lib/runtime-config.sh ---
# shellcheck shell=bash
# shellcheck disable=SC2034

config_init_common_defaults() {
  REPO_HTTPS_URL="https://github.com/obslove/arch-postinstall-apps.git"
  REPO_SSH_URL="git@github.com:obslove/arch-postinstall-apps.git"
  REPOSITORIES_DIR="${REPOSITORIES_DIR:-$HOME/Repositories}"
  INSTALL_DIR="${BOOTSTRAP_DIR:-$REPOSITORIES_DIR/arch-postinstall-apps}"
  YAY_REPO_DIR="${YAY_REPO_DIR:-$REPOSITORIES_DIR/yay}"
  YAY_SNAPSHOT_URL="${YAY_SNAPSHOT_URL:-https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz}"
  SSH_KEY_PATH="${SSH_KEY_PATH:-$HOME/.ssh/id_ed25519}"
  GITHUB_SSH_KEY_NAME=""
  LOG_FILE="${POSTINSTALL_LOG_FILE:-$HOME/Backups/arch-postinstall.log}"
  SUMMARY_FILE="${POSTINSTALL_SUMMARY_FILE:-$HOME/Backups/arch-postinstall-summary.txt}"
  CHECK_ONLY=0
  EXCLUSIVE_GITHUB_SSH_KEY=0
  SKIP_GITHUB_SSH=0
  STEP_OUTPUT_ONLY=1
  STATE_DIR="${POSTINSTALL_STATE_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/arch-postinstall-apps}"
  LOCK_DIR="${POSTINSTALL_LOCK_DIR:-$STATE_DIR/lock}"
  LOCK_HELD="${POSTINSTALL_LOCK_HELD:-0}"
}

config_init_user_shell_paths() {
  BASHRC_FILE="$HOME/.bashrc"
  ZSHRC_FILE="$HOME/.zshrc"
  FISH_CONFIG_FILE="$HOME/.config/fish/config.fish"
}

config_init_repo_paths() {
  local repo_dir="$1"

  REPO_DIR="$repo_dir"
  SCRIPT_DIR="$REPO_DIR"
  PACKAGE_FILE="$REPO_DIR/config/packages.txt"
  EXTRA_PACKAGE_FILE="$REPO_DIR/config/packages-extra.txt"
}

config_init_runtime() {
  local repo_dir="$1"

  config_init_common_defaults
  config_init_user_shell_paths
  config_init_repo_paths "$repo_dir"
  SYSTEM_UPDATED="${POSTINSTALL_BOOTSTRAP_UPDATED:-${POSTINSTALL_SYSTEM_UPDATED:-0}}"
}

config_init_bootstrap() {
  config_init_common_defaults
  config_init_user_shell_paths
  config_init_repo_paths "$INSTALL_DIR"
  SYSTEM_UPDATED=0
}

config_finalize() {
  readonly REPO_DIR
  readonly SCRIPT_DIR
  readonly PACKAGE_FILE
  readonly EXTRA_PACKAGE_FILE
  readonly BASHRC_FILE
  readonly ZSHRC_FILE
  readonly FISH_CONFIG_FILE
  readonly REPO_HTTPS_URL
  readonly REPO_SSH_URL
  readonly REPOSITORIES_DIR
  readonly INSTALL_DIR
  readonly YAY_REPO_DIR
  readonly YAY_SNAPSHOT_URL
  readonly SSH_KEY_PATH
  readonly GITHUB_SSH_KEY_NAME
  readonly LOG_FILE
  readonly SUMMARY_FILE
  readonly CHECK_ONLY
  readonly EXCLUSIVE_GITHUB_SSH_KEY
  readonly SKIP_GITHUB_SSH
  readonly STEP_OUTPUT_ONLY
  readonly STATE_DIR
  readonly LOCK_DIR
  readonly SYSTEM_UPDATED
}
# --- end: scripts/lib/runtime-config.sh ---

# --- begin: scripts/lib/step-result.sh ---
# shellcheck shell=bash
# shellcheck disable=SC2034

step_result_reset() {
  STEP_RESULT_STATUS=""
  STEP_RESULT_MESSAGE=""
  STEP_RESULT_SUMMARY_PRINTED=0
}

step_result_success() {
  STEP_RESULT_STATUS="success"
  STEP_RESULT_MESSAGE="${1:-}"
}

step_result_skipped() {
  STEP_RESULT_STATUS="skipped"
  STEP_RESULT_MESSAGE="${1:-}"
}

step_result_soft_fail() {
  STEP_RESULT_STATUS="soft_fail"
  STEP_RESULT_MESSAGE="${1:-}"
}

step_result_hard_fail() {
  STEP_RESULT_STATUS="hard_fail"
  STEP_RESULT_MESSAGE="${1:-}"
}
# --- end: scripts/lib/step-result.sh ---

# --- begin: scripts/lib/ui.sh ---
# shellcheck shell=bash
# shellcheck disable=SC2034

init_output_styles() {
  style_reset=""
  style_step=""
  style_detail=""
  style_success=""
  style_warning=""
  style_error=""
  style_muted=""

  if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
    style_reset=$'\033[0m'
    style_step=$'\033[1;36m'
    style_detail=$'\033[0;37m'
    style_success=$'\033[1;32m'
    style_warning=$'\033[1;33m'
    style_error=$'\033[1;31m'
    style_muted=$'\033[0;90m'
  fi
}

init_logging() {
  if [[ "${POSTINSTALL_LOG_INITIALIZED:-0}" == "1" ]]; then
    return
  fi

  mkdir -p "$(dirname "$LOG_FILE")"
  touch "$LOG_FILE"

  export POSTINSTALL_LOG_FILE="$LOG_FILE"
  export POSTINSTALL_LOG_INITIALIZED=1

  exec > >(tee -a "$LOG_FILE") 2>&1
}

write_log_only() {
  if [[ "${POSTINSTALL_LOG_INITIALIZED:-0}" != "1" ]]; then
    return 0
  fi

  printf '%s\n' "$1" >>"$LOG_FILE"
}

style_text() {
  local style="$1"
  local text="$2"

  if [[ -z "$style" ]]; then
    printf '%s' "$text"
    return 0
  fi

  printf '%s%s%s' "$style" "$text" "$style_reset"
}

emit_notice() {
  local symbol="$1"
  local style="$2"
  local message="$3"
  local line_prefix=""

  if [[ "$step_open" == "1" ]]; then
    line_prefix="│  "
  fi

  printf '%s%s %s\n' "$line_prefix" "$(style_text "$style" "$symbol")" "$message"
}

set_step_total() {
  step_total="$1"
}

announce_step() {
  local title="$1"
  local header=""

  close_step_block
  step_counter=$((step_counter + 1))
  if (( step_total > 0 )); then
    header=$(printf 'Etapa %02d/%02d • %s' "$step_counter" "$step_total" "$title")
  else
    header=$(printf 'Etapa %02d • %s' "$step_counter" "$title")
  fi
  echo
  printf '%s %s\n' "$(style_text "$style_step" "╭─")" "$(style_text "$style_step" "$header")"
  step_open=1
}

announce_detail() {
  if [[ "$STEP_OUTPUT_ONLY" == "1" ]]; then
    if [[ "$1" == *"Etapa ignorada."* || "$1" == Instalando\ via\ pacman:* || "$1" == Instalando\ via\ AUR:* ]]; then
      write_log_only "$1"
      return 0
    fi
    printf '│  %s %s\n' "$(style_text "$style_detail" "•")" "$1"
    return 0
  fi

  printf '│  %s %s\n' "$(style_text "$style_detail" "•")" "$1"
}

announce_warning() {
  emit_notice "!" "$style_warning" "$1"
}

announce_error() {
  emit_notice "x" "$style_error" "$1"
}

announce_prompt() {
  emit_notice "?" "$style_step" "$1"
}

print_summary_section() {
  local title="$1"
  echo "│"
  printf '│  %s\n' "$(style_text "$style_step" "$title")"
}

print_summary_item() {
  local label="$1"
  local value="$2"
  local label_length=0
  local padding_width=22

  label_length="$(printf '%s' "$label" | wc -m | tr -d '[:space:]')"
  if [[ -z "$label_length" ]]; then
    label_length=0
  fi
  if (( label_length < padding_width )); then
    printf '│  %s %s%*s %s\n' "$(style_text "$style_detail" "•")" "$label" "$((padding_width - label_length))" "" "$value"
    return 0
  fi

  printf '│  %s %s %s\n' "$(style_text "$style_detail" "•")" "$label" "$value"
}

close_step_block() {
  if [[ "$step_open" != "1" ]]; then
    return 0
  fi

  style_text "$style_muted" "╰─"
  printf '\n'
  step_open=0
}
# --- end: scripts/lib/ui.sh ---

# --- begin: scripts/lib/pipeline.sh ---
# shellcheck shell=bash

PIPELINE_STEP_IDS=()
PIPELINE_STEP_MODES=()
PIPELINE_STEP_TITLES=()
PIPELINE_STEP_FUNCTIONS=()
PIPELINE_STEP_COUNT_FLAGS=()
PIPELINE_STEP_ARGS=()

pipeline_reset() {
  PIPELINE_STEP_IDS=()
  PIPELINE_STEP_MODES=()
  PIPELINE_STEP_TITLES=()
  PIPELINE_STEP_FUNCTIONS=()
  PIPELINE_STEP_COUNT_FLAGS=()
  PIPELINE_STEP_ARGS=()
}

pipeline_add_step() {
  local step_id="$1"
  local step_mode="$2"
  local step_title="$3"
  local step_function="$4"
  local step_count_flag="${5:-1}"
  local step_args="${6:-}"

  PIPELINE_STEP_IDS+=("$step_id")
  PIPELINE_STEP_MODES+=("$step_mode")
  PIPELINE_STEP_TITLES+=("$step_title")
  PIPELINE_STEP_FUNCTIONS+=("$step_function")
  PIPELINE_STEP_COUNT_FLAGS+=("$step_count_flag")
  PIPELINE_STEP_ARGS+=("$step_args")
}

pipeline_step_matches_mode() {
  local step_mode="$1"
  local execution_mode="$2"

  [[ "$step_mode" == "all" || "$step_mode" == "$execution_mode" ]]
}

pipeline_contains_step_id() {
  local step_id="$1"
  local existing_id

  for existing_id in "${PIPELINE_STEP_IDS[@]}"; do
    [[ "$existing_id" == "$step_id" ]] && return 0
  done

  return 1
}

pipeline_count_steps_for_mode() {
  local execution_mode="$1"
  local total=0
  local index

  for index in "${!PIPELINE_STEP_IDS[@]}"; do
    if ! pipeline_step_matches_mode "${PIPELINE_STEP_MODES[$index]}" "$execution_mode"; then
      continue
    fi

    [[ "${PIPELINE_STEP_COUNT_FLAGS[$index]:-0}" == "1" ]] || continue
    total=$((total + 1))
  done

  printf '%s\n' "$total"
}

run_pipeline_steps() {
  local execution_mode="$1"
  local result_handler="${2:-}"
  local index=0
  local step_title
  local step_function
  local step_count_flag
  local step_args

  while (( index < ${#PIPELINE_STEP_IDS[@]} )); do
    if ! pipeline_step_matches_mode "${PIPELINE_STEP_MODES[$index]}" "$execution_mode"; then
      index=$((index + 1))
      continue
    fi

    step_title="${PIPELINE_STEP_TITLES[$index]}"
    step_function="${PIPELINE_STEP_FUNCTIONS[$index]}"
    step_count_flag="${PIPELINE_STEP_COUNT_FLAGS[$index]:-0}"
    step_args="${PIPELINE_STEP_ARGS[$index]}"

    if [[ "$step_count_flag" == "1" && -n "$step_title" ]]; then
      announce_step "$step_title"
    fi

    if [[ -n "$step_args" ]]; then
      "$step_function" "$step_args"
    else
      "$step_function"
    fi

    if [[ -n "$result_handler" ]]; then
      "$result_handler"
    fi

    index=$((index + 1))
  done
}
# --- end: scripts/lib/pipeline.sh ---

# --- begin: scripts/lib/step-manifest.sh ---
# shellcheck shell=bash
# shellcheck disable=SC2034

STEP_DEFINITION_IDS=()
declare -Ag STEP_DEFINITION_MODES=()
declare -Ag STEP_DEFINITION_TITLES=()
declare -Ag STEP_DEFINITION_FUNCTIONS=()
declare -Ag STEP_DEFINITION_COUNT_FLAGS=()

register_step_definition() {
  local step_id="$1"
  local step_mode="$2"
  local step_title="$3"
  local step_function="$4"
  local count_for_progress="${5:-1}"

  STEP_DEFINITION_IDS+=("$step_id")
  STEP_DEFINITION_MODES["$step_id"]="$step_mode"
  STEP_DEFINITION_TITLES["$step_id"]="$step_title"
  STEP_DEFINITION_FUNCTIONS["$step_id"]="$step_function"
  STEP_DEFINITION_COUNT_FLAGS["$step_id"]="$count_for_progress"
}

step_definition_mode() {
  printf '%s\n' "${STEP_DEFINITION_MODES[$1]:-}"
}

step_definition_title() {
  printf '%s\n' "${STEP_DEFINITION_TITLES[$1]:-}"
}

step_definition_function() {
  printf '%s\n' "${STEP_DEFINITION_FUNCTIONS[$1]:-}"
}

step_definition_count_flag() {
  printf '%s\n' "${STEP_DEFINITION_COUNT_FLAGS[$1]:-0}"
}

append_registered_step() {
  local step_id="$1"
  local step_args="${2:-}"
  local step_mode=""
  local step_title=""
  local step_function=""
  local step_count_flag="0"

  step_mode="$(step_definition_mode "$step_id")"
  step_title="$(step_definition_title "$step_id")"
  step_function="$(step_definition_function "$step_id")"
  step_count_flag="$(step_definition_count_flag "$step_id")"

  [[ -n "$step_mode" && -n "$step_function" ]] || {
    printf 'Erro: etapa não registrada: %s\n' "$step_id" >&2
    return 1
  }

  pipeline_add_step "$step_id" "$step_mode" "$step_title" "$step_function" "$step_count_flag" "$step_args"
}

append_runtime_component_steps() {
  local phase="$1"
  local component_ids=()
  local component_id
  local pipeline_title=""
  local pipeline_function=""

  case "$phase" in
    pre_package)
      mapfile -t component_ids < <(component_pre_package_pipeline_ids)
      ;;
    post_package)
      mapfile -t component_ids < <(component_post_package_pipeline_ids)
      ;;
    *)
      printf 'Erro: fase de pipeline desconhecida: %s\n' "$phase" >&2
      return 1
      ;;
  esac

  for component_id in "${component_ids[@]}"; do
    pipeline_title="$(component_pipeline_title "$component_id")"
    pipeline_function="$(component_pipeline_step_function "$component_id")"
    pipeline_add_step "$component_id" "install" "$pipeline_title" "$pipeline_function" "1"
  done
}

append_runtime_install_pipeline() {
  local package_array_name="$1"
  local origin_status=0

  append_registered_step "create_directories"
  append_registered_step "ensure_multilib"
  append_registered_step "update_system"
  append_registered_step "install_local_support_packages"
  append_runtime_component_steps "pre_package"

  if target_packages_have_official_entries "$package_array_name"; then
    append_registered_step "prepare_package_installation"
    append_registered_step "install_official_packages" "$package_array_name"
  else
    origin_status=$?
    if [[ "$origin_status" != "1" ]]; then
      return 1
    fi
  fi

  if target_packages_have_aur_entries "$package_array_name"; then
    if ! pipeline_contains_step_id "prepare_package_installation"; then
      append_registered_step "prepare_package_installation"
    fi
    append_registered_step "install_aur_packages" "$package_array_name"
  else
    origin_status=$?
    if [[ "$origin_status" != "1" ]]; then
      return 1
    fi
  fi

  if pipeline_contains_step_id "prepare_package_installation"; then
    append_registered_step "finalize_package_installation"
  fi

  append_runtime_component_steps "post_package"
  append_registered_step "final_verification" "$package_array_name"
}

define_runtime_pipeline() {
  local package_array_name="$1"

  pipeline_reset
  append_registered_step "runtime_validate_environment"
  append_registered_step "load_configuration" "$package_array_name"

  if [[ "$CHECK_ONLY" == "1" ]]; then
    append_registered_step "check_only_verification" "$package_array_name"
  fi
}

define_bootstrap_pipeline() {
  local missing_packages_array_name="$1"

  pipeline_reset
  append_registered_step "bootstrap_validate_environment"
  append_registered_step "bootstrap_check_dependencies" "$missing_packages_array_name"

  if bootstrap_missing_packages_present "$missing_packages_array_name"; then
    append_registered_step "bootstrap_install_dependencies" "$missing_packages_array_name"
  fi

  append_registered_step "bootstrap_sync_repo"
}

bootstrap_missing_packages_present() {
  local array_name="$1"
  declare -n missing_packages="$array_name"

  (( ${#missing_packages[@]} > 0 ))
}

register_step_definition "runtime_validate_environment" "all" "Validando ambiente..." "runtime_validate_environment_step"
register_step_definition "load_configuration" "all" "Carregando configuração..." "load_configuration_step"
register_step_definition "check_only_verification" "check" "Executando verificação sem alterações..." "check_only_step"
register_step_definition "create_directories" "install" "Criando diretórios..." "create_directories_step"
register_step_definition "ensure_multilib" "install" "Preparando repositório multilib..." "ensure_multilib_step"
register_step_definition "update_system" "install" "Atualizando o sistema..." "update_system_step"
register_step_definition "install_local_support_packages" "install" "Instalando ferramentas de suporte..." "install_local_support_packages_step"
register_step_definition "prepare_package_installation" "install" "" "prepare_package_installation_step" "0"
register_step_definition "install_official_packages" "install" "Instalando apps oficiais..." "install_official_packages_step"
register_step_definition "install_aur_packages" "install" "Instalando apps AUR..." "install_aur_packages_step"
register_step_definition "finalize_package_installation" "install" "" "finalize_package_installation_step" "0"
register_step_definition "final_verification" "install" "Validando instalação..." "final_verification_step"

register_step_definition "bootstrap_validate_environment" "bootstrap" "Validando ambiente..." "bootstrap_validate_environment_step"
register_step_definition "bootstrap_check_dependencies" "bootstrap" "Verificando dependências iniciais já instaladas..." "bootstrap_check_dependencies_step"
register_step_definition "bootstrap_install_dependencies" "bootstrap" "Instalando dependências iniciais..." "bootstrap_install_dependencies_step"
register_step_definition "bootstrap_sync_repo" "bootstrap" "Sincronizando repositório..." "bootstrap_sync_repo_step"
# --- end: scripts/lib/step-manifest.sh ---

# --- begin: scripts/lib/process.sh ---
# shellcheck shell=bash

append_array_item() {
  local array_name="$1"
  local value="$2"
  local existing
  # shellcheck disable=SC2178
  declare -n target_array="$array_name"

  for existing in "${target_array[@]}"; do
    [[ "$existing" == "$value" ]] && return 0
  done

  target_array+=("$value")
}

package_is_installed() {
  pacman -Q "$1" >/dev/null 2>&1
}

run_with_terminal_stdin() {
  if [[ -r /dev/tty ]]; then
    "$@" </dev/tty
    return
  fi

  "$@"
}

collect_missing_packages() {
  local array_name="$1"
  shift
  local package_name
  # shellcheck disable=SC2178
  declare -n target_array="$array_name"

  target_array=()
  for package_name in "$@"; do
    if ! package_is_installed "$package_name"; then
      target_array+=("$package_name")
    fi
  done
}

run_log_only() {
  if [[ "$STEP_OUTPUT_ONLY" == "1" ]]; then
    "$@" </dev/null >>"$LOG_FILE" 2>&1
    return
  fi

  "$@" </dev/null 2>&1 | sed 's/^/│    /'
  return "${PIPESTATUS[0]}"
}

run_interactive_log_only() {
  if [[ "$STEP_OUTPUT_ONLY" == "1" ]]; then
    run_with_terminal_stdin "$@" >>"$LOG_FILE" 2>&1
    return
  fi

  run_with_terminal_stdin "$@" 2>&1 | sed 's/^/│    /'
  return "${PIPESTATUS[0]}"
}

retry() {
  "$@"
}

retry_log_only() {
  run_log_only "$@"
}

retry_interactive_log_only() {
  run_interactive_log_only "$@"
}
# --- end: scripts/lib/process.sh ---

# --- begin: scripts/lib/locking.sh ---
# shellcheck shell=bash

checkpoint_file() {
  printf '%s/checkpoints/%s.done\n' "$STATE_DIR" "$1"
}

has_checkpoint() {
  [[ -f "$(checkpoint_file "$1")" ]]
}

mark_checkpoint() {
  mkdir -p "$STATE_DIR/checkpoints"
  touch "$(checkpoint_file "$1")"
}

register_cleanup_path() {
  cleanup_paths+=("$1")
}

acquire_lock() {
  local existing_pid=""

  if [[ "$LOCK_HELD" == "1" ]]; then
    return
  fi

  mkdir -p "$STATE_DIR"
  if mkdir "$LOCK_DIR" 2>/dev/null; then
    printf '%s\n' "$$" >"$LOCK_DIR/pid"
    register_cleanup_path "$LOCK_DIR"
    export POSTINSTALL_LOCK_HELD=1
    LOCK_HELD=1
    return
  fi

  if [[ -f "$LOCK_DIR/pid" ]]; then
    existing_pid="$(<"$LOCK_DIR/pid")"
  fi

  if [[ -z "$existing_pid" ]] || ! kill -0 "$existing_pid" 2>/dev/null; then
    announce_warning "Foi detectado um lock órfão. Limpando a execução anterior."
    rm -rf -- "$LOCK_DIR"
    if mkdir "$LOCK_DIR" 2>/dev/null; then
      printf '%s\n' "$$" >"$LOCK_DIR/pid"
      register_cleanup_path "$LOCK_DIR"
      export POSTINSTALL_LOCK_HELD=1
      LOCK_HELD=1
      return
    fi
  fi

  announce_error "Já existe outra execução do script em andamento."
  if [[ -f "$LOCK_DIR/pid" ]]; then
    announce_error "PID atual do lock: $(<"$LOCK_DIR/pid")"
  fi
  exit 1
}

cleanup() {
  local path

  for path in "${cleanup_paths[@]}"; do
    [[ -n "$path" ]] || continue
    rm -rf -- "$path"
  done
}
# --- end: scripts/lib/locking.sh ---

# --- begin: scripts/lib/env.sh ---
# shellcheck shell=bash

ensure_not_root() {
  if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
    announce_error "Execute este script como usuário comum, e não como root."
    exit 1
  fi
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    announce_error "Comando obrigatório não encontrado: $1"
    exit 1
  fi
}

canonicalize_path() {
  if ! command -v realpath >/dev/null 2>&1; then
    announce_error "Comando obrigatório não encontrado: realpath"
    return 1
  fi

  realpath -m -- "$1"
}

require_exact_path() {
  local label="$1"
  local actual_path="$2"
  local expected_path="$3"
  local resolved_actual=""
  local resolved_expected=""

  [[ -n "$actual_path" && -n "$expected_path" ]] || {
    announce_error "Caminho inválido para $label."
    return 1
  }

  resolved_actual="$(canonicalize_path "$actual_path")" || return 1
  resolved_expected="$(canonicalize_path "$expected_path")" || return 1

  if [[ "$resolved_actual" != "$resolved_expected" ]]; then
    announce_error "$label fora do caminho gerenciado esperado: $actual_path"
    announce_error "Esperado: $resolved_expected"
    return 1
  fi
}

validate_managed_paths() {
  local expected_repositories_dir="$HOME/Repositories"
  local expected_install_dir="$expected_repositories_dir/arch-postinstall-apps"
  local expected_yay_repo_dir="$expected_repositories_dir/yay"
  local expected_state_dir="${XDG_STATE_HOME:-$HOME/.local/state}/arch-postinstall-apps"
  local expected_lock_dir="$expected_state_dir/lock"

  require_exact_path "REPOSITORIES_DIR" "$REPOSITORIES_DIR" "$expected_repositories_dir" || exit 1
  require_exact_path "INSTALL_DIR" "$INSTALL_DIR" "$expected_install_dir" || exit 1
  require_exact_path "YAY_REPO_DIR" "$YAY_REPO_DIR" "$expected_yay_repo_dir" || exit 1
  require_exact_path "STATE_DIR" "$STATE_DIR" "$expected_state_dir" || exit 1
  require_exact_path "LOCK_DIR" "$LOCK_DIR" "$expected_lock_dir" || exit 1
}

get_host_name() {
  if command -v hostname >/dev/null 2>&1; then
    hostname
    return
  fi

  if command -v hostnamectl >/dev/null 2>&1; then
    hostnamectl hostname 2>/dev/null
    return
  fi

  if [[ -f /etc/hostname ]]; then
    cat /etc/hostname
    return
  fi

  uname -n
}

sanitize_label() {
  printf '%s' "$1" | tr -cs '[:alnum:].@_-' '-'
}

is_wayland_session() {
  [[ "${XDG_SESSION_TYPE:-}" == "wayland" || -n "${WAYLAND_DISPLAY:-}" ]]
}

is_hyprland_session() {
  [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] || \
    [[ "${XDG_CURRENT_DESKTOP:-}" == *Hyprland* ]] || \
    [[ "${DESKTOP_SESSION:-}" == "hyprland" ]]
}

is_supported_session() {
  is_wayland_session && is_hyprland_session
}

ensure_supported_session() {
  if is_supported_session; then
    return 0
  fi

  announce_error "Este script foi ajustado para Wayland com Hyprland."
  announce_error "Sessão atual: XDG_SESSION_TYPE='${XDG_SESSION_TYPE:-}', XDG_CURRENT_DESKTOP='${XDG_CURRENT_DESKTOP:-}', DESKTOP_SESSION='${DESKTOP_SESSION:-}'"
  exit 1
}

ensure_arch() {
  if [[ ! -f /etc/arch-release ]]; then
    announce_error "Este script foi feito para Arch Linux."
    exit 1
  fi
}

github_ssh_expected() {
  [[ "$SKIP_GITHUB_SSH" != "1" ]]
}

github_ssh_force_reconcile() {
  [[ "$EXCLUSIVE_GITHUB_SSH_KEY" == "1" || -n "$GITHUB_SSH_KEY_NAME" ]]
}
# --- end: scripts/lib/env.sh ---

# --- begin: scripts/lib/ops.sh ---
# shellcheck shell=bash
# shellcheck source-path=SCRIPTDIR

ops_sudo_auth() {
  run_with_terminal_stdin sudo -v
}

ops_pacman_upgrade_and_install_needed() {
  retry_interactive_log_only sudo pacman -Syu --needed --noconfirm "$@"
}

ops_pacman_upgrade_full() {
  retry_interactive_log_only sudo pacman -Syu --noconfirm
}

ops_pacman_install_needed() {
  retry_interactive_log_only sudo pacman -S --needed --noconfirm "$@"
}

ops_pacman_remove_recursive() {
  retry_interactive_log_only sudo pacman -Rns --noconfirm "$@"
}

ops_pacman_refresh_databases() {
  run_interactive_log_only sudo pacman -Syy --noconfirm
}

ops_backup_pacman_conf() {
  local backup_path="$1"

  sudo cp /etc/pacman.conf "$backup_path"
}

ops_enable_multilib_config() {
  sudo sed -i \
    '/^[[:space:]]*#\[multilib\][[:space:]]*$/,/^[[:space:]]*#Include = \/etc\/pacman.d\/mirrorlist[[:space:]]*$/ s/^[[:space:]]*#//' \
    /etc/pacman.conf
}

ops_download_file() {
  local source_url="$1"
  local destination_path="$2"

  retry curl -fsSL "$source_url" -o "$destination_path"
}

ops_extract_tar_gz() {
  local archive_path="$1"
  local destination_dir="$2"

  tar -xzf "$archive_path" -C "$destination_dir"
}

ops_build_yay_package() {
  local yay_dir="$1"

  retry_log_only build_yay "$yay_dir"
}

ops_git_remote_add_origin() {
  local repo_dir="$1"
  local origin_url="$2"

  git -C "$repo_dir" remote add origin "$origin_url"
}

ops_git_remote_set_origin() {
  local repo_dir="$1"
  local origin_url="$2"

  git -C "$repo_dir" remote set-url origin "$origin_url"
}

ops_git_fetch_origin() {
  local repo_dir="$1"

  retry_log_only git -C "$repo_dir" fetch origin
}

ops_git_checkout_main() {
  local repo_dir="$1"

  run_log_only git -C "$repo_dir" checkout main
}

ops_git_checkout_main_from_origin() {
  local repo_dir="$1"

  run_log_only git -C "$repo_dir" checkout -b main origin/main
}

ops_git_pull_main_ff_only() {
  local repo_dir="$1"

  retry_log_only git -C "$repo_dir" pull --ff-only origin main
}

ops_git_clone_main() {
  local repo_url="$1"
  local repo_dir="$2"

  retry_log_only git clone --branch main --single-branch "$repo_url" "$repo_dir"
}

ops_gh_auth_login() {
  run_gh_auth_flow auth login --web --git-protocol ssh --scopes admin:public_key
}

ops_gh_auth_refresh_admin_public_key() {
  run_gh_auth_flow auth refresh -h github.com -s admin:public_key
}

ops_gh_delete_ssh_key() {
  local key_id="$1"

  retry gh api --method DELETE "user/keys/$key_id"
}

ops_gh_create_ssh_key() {
  local key_name="$1"
  local public_key="$2"

  retry gh api user/keys --method POST -f "title=$key_name" -f "key=$public_key" --jq '.id'
}

ops_npm_config_set_prefix() {
  local prefix_path="$1"

  run_log_only npm config set prefix "$prefix_path"
}

ops_npm_install_codex_cli() {
  retry_log_only npm install -g @openai/codex
}

ops_ssh_regenerate_public_key() {
  local private_key_path="$1"
  local public_key_path="$2"

  ssh-keygen -y -f "$private_key_path" >"$public_key_path"
}

ops_ssh_generate_key_pair() {
  local key_comment="$1"
  local key_path="$2"

  ssh-keygen -t ed25519 -C "$key_comment" -f "$key_path" -N ""
}

ops_systemctl_user_daemon_reload() {
  run_log_only systemctl --user daemon-reload
}

ops_systemctl_user_start() {
  run_log_only systemctl --user start "$@"
}

ops_aur_install_needed() {
  local helper_name="$1"
  shift

  retry_log_only "$helper_name" -S --needed --noconfirm "$@"
}
# --- end: scripts/lib/ops.sh ---

# --- begin: scripts/lib/repo.sh ---
# shellcheck shell=bash
# shellcheck source-path=SCRIPTDIR
# shellcheck source=scripts/lib/shellcheck-runtime.sh
# shellcheck source=scripts/lib/ops.sh

if false; then
  source "$SCRIPT_DIR/scripts/lib/shellcheck-runtime.sh"
  source "$SCRIPT_DIR/scripts/lib/ops.sh"
fi

ensure_repo_origin_remote() {
  local repo_dir="$1"
  local desired_origin_url="${2:-$REPO_HTTPS_URL}"
  local current_origin_url=""
  current_origin_url="$(git -C "$repo_dir" remote get-url origin 2>/dev/null || true)"

  if [[ -z "$current_origin_url" ]]; then
    ops_git_remote_add_origin "$repo_dir" "$desired_origin_url"
    return
  fi

  if [[ "$current_origin_url" != "$REPO_HTTPS_URL" && "$current_origin_url" != "$REPO_SSH_URL" ]]; then
    announce_detail "Foi detectado um remoto origin personalizado em $repo_dir. A configuração atual será mantida."
    return
  fi

  if [[ "$current_origin_url" != "$desired_origin_url" ]]; then
    ops_git_remote_set_origin "$repo_dir" "$desired_origin_url"
  fi
}

get_repo_branch() {
  local repo_dir="$1"
  local branch_name=""

  if ! git -C "$repo_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    return 1
  fi

  branch_name="$(git -C "$repo_dir" symbolic-ref --quiet --short HEAD 2>/dev/null || true)"
  if [[ -n "$branch_name" ]]; then
    printf '%s\n' "$branch_name"
    return 0
  fi

  branch_name="$(git -C "$repo_dir" rev-parse --short HEAD 2>/dev/null || true)"
  [[ -n "$branch_name" ]] || return 1
  printf 'detached@%s\n' "$branch_name"
}

current_repo_origin_status() {
  local repo_dir="$1"
  local current_origin_url=""

  current_origin_url="$(git -C "$repo_dir" remote get-url origin 2>/dev/null || true)"
  case "$current_origin_url" in
    "$REPO_SSH_URL")
      printf '%s\n' "ssh"
      ;;
    "$REPO_HTTPS_URL")
      printf '%s\n' "https"
      ;;
    "")
      printf '%s\n' "ausente"
      ;;
    *)
      printf '%s\n' "personalizado"
      ;;
  esac
}

current_repo_commit_short() {
  local repo_dir="$1"
  local commit_hash=""

  commit_hash="$(git -C "$repo_dir" rev-parse --short HEAD 2>/dev/null || true)"
  [[ -n "$commit_hash" ]] || {
    printf '%s\n' "indisponível"
    return 0
  }

  printf '%s\n' "$commit_hash"
}
# --- end: scripts/lib/repo.sh ---

# --- begin: scripts/bootstrap/repo-sync.sh ---
# shellcheck shell=bash

repo_is_dirty() {
  ! git -C "$INSTALL_DIR" diff --quiet --no-ext-diff || \
    ! git -C "$INSTALL_DIR" diff --cached --quiet --no-ext-diff || \
    [[ -n "$(git -C "$INSTALL_DIR" status --porcelain --untracked-files=normal)" ]]
}

sync_repo() {
  local current_branch=""
  local fetched_origin=0

  mkdir -p "$(dirname "$INSTALL_DIR")"

  if [[ -d "$INSTALL_DIR/.git" ]]; then
    announce_detail "Atualizando clone gerenciado..."
    if repo_is_dirty; then
      current_branch="$(get_repo_branch "$INSTALL_DIR" 2>/dev/null || true)"
      if [[ -n "$current_branch" && "$current_branch" != "main" ]]; then
        announce_error "O clone gerenciado está com mudanças locais na branch '$current_branch'."
        announce_error "Não dá para executar com segurança a branch 'main' sem limpar ou mover essas mudanças."
        return 1
      fi

      announce_warning "O repositório local tem alterações. A atualização automática será ignorada."
      return 0
    fi

    if ! ensure_repo_origin_remote "$INSTALL_DIR" "$REPO_HTTPS_URL"; then
      announce_error "Não foi possível ajustar o remoto origin do clone gerenciado."
      return 1
    fi

    if retry_log_only git -C "$INSTALL_DIR" fetch origin; then
      fetched_origin=1
    else
      announce_warning "Falha ao buscar atualizações de origin. O script tentará usar a cópia local."
    fi

    if git -C "$INSTALL_DIR" show-ref --verify --quiet "refs/heads/main"; then
      if ! run_log_only git -C "$INSTALL_DIR" checkout main; then
        announce_error "Não foi possível trocar para a branch local 'main'."
        return 1
      fi
    elif git -C "$INSTALL_DIR" show-ref --verify --quiet "refs/remotes/origin/main"; then
      if ! run_log_only git -C "$INSTALL_DIR" checkout -b main origin/main; then
        announce_error "Não foi possível criar a branch local 'main' a partir de origin."
        return 1
      fi
    elif [[ "$fetched_origin" == "0" ]]; then
      announce_error "Não foi possível atualizar origin e a branch 'main' não existe localmente."
      announce_error "Verifique acesso ao GitHub ou recupere um clone local válido."
      return 1
    else
      announce_error "Branch 'main' não encontrada no repositório local nem em origin."
      return 1
    fi

    if [[ "$fetched_origin" == "0" ]]; then
      announce_warning "O 'git pull' será ignorado porque o fetch de origin falhou. O script continuará com a branch local."
      return 0
    fi

    if ! retry_log_only git -C "$INSTALL_DIR" pull --ff-only origin main; then
      announce_warning "Falha ao atualizar 'main' com 'git pull --ff-only'. O script continuará com a cópia atual."
    fi
    return 0
  fi

  if [[ -e "$INSTALL_DIR" ]]; then
    announce_error "$INSTALL_DIR já existe e não é um repositório git."
    return 1
  fi

  announce_detail "Clonando repositório pela primeira vez..."
  if ! retry_log_only git clone --branch main --single-branch "$REPO_HTTPS_URL" "$INSTALL_DIR"; then
    announce_error "Falha ao clonar 'main' de $REPO_HTTPS_URL."
    announce_error "Verifique acesso ao GitHub e se a branch existe no remoto."
    return 1
  fi
}
# --- end: scripts/bootstrap/repo-sync.sh ---

# --- begin: scripts/bootstrap/entrypoint.sh ---
# shellcheck shell=bash
# shellcheck disable=SC2034
# shellcheck source-path=SCRIPTDIR
# shellcheck source=scripts/lib/cli.sh
# shellcheck source=scripts/lib/runtime-config.sh
# shellcheck source=scripts/lib/step-result.sh
# shellcheck source=scripts/lib/ui.sh
# shellcheck source=scripts/lib/pipeline.sh
# shellcheck source=scripts/lib/step-manifest.sh
# shellcheck source=scripts/lib/process.sh
# shellcheck source=scripts/lib/locking.sh
# shellcheck source=scripts/lib/env.sh
# shellcheck source=scripts/lib/ops.sh
# shellcheck source=scripts/lib/repo.sh
# shellcheck source=scripts/bootstrap/repo-sync.sh

if false; then
  source "$SCRIPT_DIR/scripts/lib/cli.sh"
  source "$SCRIPT_DIR/scripts/lib/runtime-config.sh"
  source "$SCRIPT_DIR/scripts/lib/step-result.sh"
  source "$SCRIPT_DIR/scripts/lib/ui.sh"
  source "$SCRIPT_DIR/scripts/lib/pipeline.sh"
  source "$SCRIPT_DIR/scripts/lib/step-manifest.sh"
  source "$SCRIPT_DIR/scripts/lib/process.sh"
  source "$SCRIPT_DIR/scripts/lib/locking.sh"
  source "$SCRIPT_DIR/scripts/lib/env.sh"
  source "$SCRIPT_DIR/scripts/lib/ops.sh"
  source "$SCRIPT_DIR/scripts/lib/repo.sh"
  source "$SCRIPT_DIR/scripts/bootstrap/repo-sync.sh"
fi

SELF_PATH="${BASH_SOURCE[0]:-$0}"
BOOTSTRAP_SCRIPT_DIR="$(cd "$(dirname "$SELF_PATH")" && pwd)"
LOCAL_MAIN="$BOOTSTRAP_SCRIPT_DIR/scripts/install/main.sh"

if [[ -f "$SELF_PATH" && -f "$LOCAL_MAIN" ]]; then
  exec bash "$LOCAL_MAIN" "$@"
fi

config_init_bootstrap
BOOTSTRAP_PACKAGES=(
  ca-certificates
  git
  curl
  tar
)
BOOTSTRAP_MISSING_PACKAGES=()
BOOTSTRAP_SYSTEM_UPDATED=0

cleanup_paths=()
step_counter=0
step_open=0
step_total=0
STEP_RESULT_STATUS=""
STEP_RESULT_MESSAGE=""

init_output_styles

handle_bootstrap_step_result_or_exit() {
  case "${STEP_RESULT_STATUS:-}" in
    success|skipped|"")
      return 0
      ;;
    hard_fail)
      if [[ -n "${STEP_RESULT_MESSAGE:-}" ]]; then
        announce_error "$STEP_RESULT_MESSAGE"
      fi
      exit 1
      ;;
    *)
      announce_error "Resultado de etapa desconhecido no bootstrap: ${STEP_RESULT_STATUS:-indefinido}"
      exit 1
      ;;
  esac
}

bootstrap_validate_environment_step() {
  step_result_reset

  if ! ensure_arch; then
    step_result_hard_fail "Este bootstrap só pode ser executado em Arch Linux."
    return 0
  fi

  if ! ensure_supported_session; then
    step_result_hard_fail "A sessão atual não é compatível com o bootstrap."
    return 0
  fi

  if ! require_command pacman; then
    step_result_hard_fail "O comando 'pacman' é obrigatório para continuar."
    return 0
  fi

  if ! require_command sudo; then
    step_result_hard_fail "O comando 'sudo' é obrigatório para continuar."
    return 0
  fi

  announce_prompt "Autenticando sudo..."
  if ! run_with_terminal_stdin sudo -v; then
    step_result_hard_fail "Não foi possível autenticar o sudo."
    return 0
  fi

  init_logging
  step_result_success "O ambiente de bootstrap foi validado."
}

bootstrap_check_dependencies_step() {
  local array_name="$1"
  # shellcheck disable=SC2178
  declare -n missing_packages="$array_name"

  step_result_reset

  if ((${#missing_packages[@]} == 0)); then
    announce_detail "As dependências iniciais já estão disponíveis."
    step_result_success "As dependências iniciais já estavam disponíveis."
    return 0
  fi

  announce_detail "${#missing_packages[@]} dependência(s) inicial(is) ainda não instalada(s)."
  step_result_success "As dependências iniciais foram avaliadas."
}

bootstrap_install_dependencies_step() {
  local array_name="${1:-BOOTSTRAP_MISSING_PACKAGES}"
  # shellcheck disable=SC2178
  declare -n missing_packages="$array_name"

  step_result_reset

  if ((${#missing_packages[@]} == 0)); then
    announce_detail "As dependências iniciais já estão disponíveis. Etapa ignorada."
    step_result_skipped "As dependências iniciais já estavam disponíveis."
    return 0
  fi

  if retry_interactive_log_only sudo pacman -Syu --needed --noconfirm "${missing_packages[@]}"; then
    BOOTSTRAP_SYSTEM_UPDATED=1
    step_result_success "As dependências iniciais foram instaladas."
    return 0
  fi

  step_result_hard_fail "Não foi possível instalar as dependências iniciais."
}

bootstrap_sync_repo_step() {
  step_result_reset

  if ! require_command git; then
    step_result_hard_fail "O comando 'git' é obrigatório para sincronizar o repositório."
    return 0
  fi

  if ! require_command curl; then
    step_result_hard_fail "O comando 'curl' é obrigatório para sincronizar o repositório."
    return 0
  fi

  if ! require_command tar; then
    step_result_hard_fail "O comando 'tar' é obrigatório para sincronizar o repositório."
    return 0
  fi

  if sync_repo; then
    step_result_success "O repositório gerenciado foi sincronizado."
    return 0
  fi

  step_result_hard_fail "Não foi possível sincronizar o repositório gerenciado."
}

main() {
  parse_cli_args "$@"
  validate_managed_paths
  trap cleanup EXIT

  ensure_not_root
  acquire_lock
  collect_missing_packages BOOTSTRAP_MISSING_PACKAGES "${BOOTSTRAP_PACKAGES[@]}"
  define_bootstrap_pipeline BOOTSTRAP_MISSING_PACKAGES
  set_step_total "$(pipeline_count_steps_for_mode bootstrap)"
  run_pipeline_steps "bootstrap" "handle_bootstrap_step_result_or_exit"

  exec env \
    POSTINSTALL_BOOTSTRAP_UPDATED="$BOOTSTRAP_SYSTEM_UPDATED" \
    POSTINSTALL_LOG_FILE="$LOG_FILE" \
    POSTINSTALL_LOG_INITIALIZED=1 \
    POSTINSTALL_LOCK_HELD=1 \
    POSTINSTALL_SUMMARY_FILE="$SUMMARY_FILE" \
    POSTINSTALL_STATE_DIR="$STATE_DIR" \
    POSTINSTALL_LOCK_DIR="$LOCK_DIR" \
    SSH_KEY_PATH="$SSH_KEY_PATH" \
    REPOSITORIES_DIR="$REPOSITORIES_DIR" \
    YAY_REPO_DIR="$YAY_REPO_DIR" \
    YAY_SNAPSHOT_URL="$YAY_SNAPSHOT_URL" \
    bash "$INSTALL_DIR/scripts/install/main.sh" "$@"
}

main "$@"
# --- end: scripts/bootstrap/entrypoint.sh ---
