#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC2034
# This file is generated by `bash scripts/build-shellcheck-runtime.sh`.
# Do not edit it directly.

target_array=""
property_map=""
handler_name=""
CHECK_ONLY=""
EXCLUSIVE_GITHUB_SSH_KEY=""
SKIP_GITHUB_SSH=""
GITHUB_SSH_KEY_NAME=""
STEP_OUTPUT_ONLY=""
REPO_HTTPS_URL=""
REPO_SSH_URL=""
REPOSITORIES_DIR=""
INSTALL_DIR=""
YAY_REPO_DIR=""
YAY_SNAPSHOT_URL=""
SSH_KEY_PATH=""
LOG_FILE=""
SUMMARY_FILE=""
STATE_DIR=""
LOCK_DIR=""
LOCK_HELD=""
BASHRC_FILE=""
ZSHRC_FILE=""
FISH_CONFIG_FILE=""
REPO_DIR=""
SCRIPT_DIR=""
PACKAGE_FILE=""
EXTRA_PACKAGE_FILE=""
SYSTEM_UPDATED=""
env_assignments=""
component_outcome=""
STEP_RESULT_STATUS=""
STEP_RESULT_MESSAGE=""
STEP_RESULT_SUMMARY_PRINTED=""
style_reset=""
style_step=""
style_detail=""
style_success=""
style_warning=""
style_error=""
style_muted=""
POSTINSTALL_LOG_FILE=""
POSTINSTALL_LOG_INITIALIZED=""
line_prefix=""
step_total=""
step_counter=""
header=""
step_open=""
label_length=""
total=""
index=""
step_title=""
step_function=""
step_count_flag=""
step_args=""
step_mode=""
pipeline_title=""
pipeline_function=""
origin_status=""
missing_packages=""
POSTINSTALL_LOCK_HELD=""
existing_pid=""
resolved_actual=""
resolved_expected=""
current_origin_url=""
branch_name=""
commit_hash=""
SHARED_LIB_DIR=""
COMPONENT_CONFIG_FILE=""
created_any=""
summary_formatter=""
archive_file=""
status=""
aur_helper_name=""
GITHUB_SSH_COMPONENT_DIR=""
github_login=""
current_key=""
key_data=""
line=""
target_packages=""
package_origin=""
source_packages=""
package_previously_installed=""
output=""
verification_label=""
repair_strategy=""
repair_target=""
package_origin_status=""
should_start_services=""
should_repair_codex=""
should_repair_origin=""
execution_mode=""
changes_applied=""
host_name=""
actual_branch=""
actual_commit=""
repo_path=""
component_label=""
component_status_text=""
desktop_outcome=""
step_status=""
github_outcome=""
STATE_AUR_HELPER_NAME=""
STATE_AUR_HELPER_STATUS=""
STATE_TEMP_CLIPBOARD_PACKAGE=""
STATE_OFFICIAL_REPO_METADATA_CHECKED=""
STATE_OFFICIAL_REPO_METADATA_READY=""
temp_clipboard_package=""
ssh_dir=""
key_comment=""
key_name=""
current_key_id=""
current_key_name=""

ENABLED_SPECIAL_COMPONENTS=()
BOOTSTRAP_SUPPORT_PACKAGES=()
LOCAL_SUPPORT_PACKAGES=()
AUR_HELPER_SUPPORT_PACKAGES=()
AUR_HELPER_README_ITEMS=()
GITHUB_SSH_SUPPORT_PACKAGES=()
CODEX_CLI_PACKAGES=()
CODEX_CLI_README_ITEMS=()
DESKTOP_INTEGRATION_PACKAGES=()
DESKTOP_USER_SERVICES=()
TEMPORARY_CLIPBOARD_PACKAGES=()
COMPONENT_IDS=()
REPORT_REQUESTED_MAIN_OFFICIAL_PACKAGES=()
REPORT_REQUESTED_MAIN_AUR_PACKAGES=()
REPORT_REUSED_MAIN_OFFICIAL_PACKAGES=()
REPORT_REUSED_MAIN_AUR_PACKAGES=()
REPORT_CHANGED_MAIN_OFFICIAL_PACKAGES=()
REPORT_CHANGED_MAIN_AUR_PACKAGES=()
REPORT_REQUESTED_SUPPORT_PACKAGES=()
REPORT_REUSED_SUPPORT_PACKAGES=()
REPORT_CHANGED_SUPPORT_PACKAGES=()
REPORT_REQUESTED_ENVIRONMENT_PACKAGES=()
REPORT_REUSED_ENVIRONMENT_PACKAGES=()
REPORT_CHANGED_ENVIRONMENT_PACKAGES=()
REPORT_CHANGE_MARKERS=()
REPORT_COMPONENT_OUTCOMES=()
PIPELINE_STEP_IDS=()
PIPELINE_STEP_MODES=()
PIPELINE_STEP_TITLES=()
PIPELINE_STEP_FUNCTIONS=()
PIPELINE_STEP_COUNT_FLAGS=()
PIPELINE_STEP_ARGS=()
STEP_DEFINITION_IDS=()
target_array=()
cleanup_paths=()
target_packages=()
STATE_MAIN_OFFICIAL_PACKAGES=()
STATE_MAIN_AUR_PACKAGES=()
STATE_FAILED_OFFICIAL_PACKAGES=()
STATE_FAILED_AUR_PACKAGES=()
STATE_VERIFIED_ITEM_IDS=()
STATE_VERIFIED_ITEMS=()
STATE_MISSING_ITEM_IDS=()
STATE_MISSING_ITEMS=()
STATE_VERSION_LINES=()
STATE_SOFT_FAILURES=()
STATE_VERIFICATION_LABELS=()
STATE_VERIFICATION_KINDS=()
STATE_VERIFICATION_REPAIR_STRATEGIES=()
STATE_VERIFICATION_TARGETS=()
STATE_VERIFICATION_STATUSES=()

declare -Ag COMPONENT_LABELS=()
declare -Ag COMPONENT_PIPELINE_PHASES=()
declare -Ag COMPONENT_EXPECTED_FUNCTIONS=()
declare -Ag COMPONENT_PIPELINE_TITLES=()
declare -Ag COMPONENT_PIPELINE_STEP_FUNCTIONS=()
declare -Ag COMPONENT_SUMMARY_FORMATTERS=()
declare -Ag COMPONENT_DETECT_HANDLERS=()
declare -Ag COMPONENT_APPLY_HANDLERS=()
declare -Ag COMPONENT_VERIFY_HANDLERS=()
declare -Ag COMPONENT_CHECKPOINT_HANDLERS=()
declare -Ag COMPONENT_RUNTIME_STATUS_FLAGS=()
declare -Ag COMPONENT_CHECKPOINT_FLAGS=()
declare -Ag COMPONENT_CHECK_ONLY_DETECTION_FLAGS=()
declare -Ag COMPONENT_VERIFICATION_FLAGS=()
declare -Ag COMPONENT_SUMMARY_STATUS_FLAGS=()
declare -Ag REPORT_COMPONENT_OUTCOMES=()
declare -Ag STEP_DEFINITION_MODES=()
declare -Ag STEP_DEFINITION_TITLES=()
declare -Ag STEP_DEFINITION_FUNCTIONS=()
declare -Ag STEP_DEFINITION_COUNT_FLAGS=()
declare -Ag STATE_VERIFICATION_LABELS=()
declare -Ag STATE_VERIFICATION_KINDS=()
declare -Ag STATE_VERIFICATION_REPAIR_STRATEGIES=()
declare -Ag STATE_VERIFICATION_TARGETS=()
declare -Ag STATE_VERIFICATION_STATUSES=()

config_array_contains() {
  :
}

print_config_array() {
  :
}

print_component_ids_by_property() {
  :
}

component_enabled() {
  :
}

component_expected_always() {
  :
}

component_expected_codex_cli() {
  :
}

register_component() {
  :
}

component_registry_ids() {
  :
}

component_pre_package_pipeline_ids() {
  :
}

component_post_package_pipeline_ids() {
  :
}

component_check_only_detection_ids() {
  :
}

component_verification_ids() {
  :
}

component_summary_status_ids() {
  :
}

component_summary_label() {
  :
}

component_is_expected() {
  :
}

component_has_runtime_status() {
  :
}

component_pipeline_step_function() {
  :
}

component_pipeline_title() {
  :
}

component_summary_formatter_function() {
  :
}

component_action_handler() {
  :
}

print_usage() {
  :
}

parse_cli_args() {
  :
}

config_init_common_defaults() {
  :
}

config_init_user_shell_paths() {
  :
}

config_init_repo_paths() {
  :
}

config_init_runtime() {
  :
}

config_init_bootstrap() {
  :
}

config_finalize() {
  :
}

load_bootstrap_invocation_context() {
  :
}

load_runtime_invocation_context() {
  :
}

append_runtime_invocation_env() {
  :
}

exec_runtime_with_invocation_context() {
  :
}

execution_report_reset() {
  :
}

report_mark_change() {
  :
}

report_has_changes() {
  :
}

report_add_requested_main_official_package() {
  :
}

report_add_reused_main_official_package() {
  :
}

report_add_changed_main_official_package() {
  :
}

report_add_requested_main_aur_package() {
  :
}

report_add_reused_main_aur_package() {
  :
}

report_add_changed_main_aur_package() {
  :
}

report_add_requested_support_package() {
  :
}

report_add_reused_support_package() {
  :
}

report_add_changed_support_package() {
  :
}

report_add_requested_environment_package() {
  :
}

report_add_reused_environment_package() {
  :
}

report_add_changed_environment_package() {
  :
}

report_reset_environment_packages() {
  :
}

report_set_component_outcome() {
  :
}

report_get_component_outcome() {
  :
}

report_component_counts_as_ready() {
  :
}

step_result_reset() {
  :
}

step_result_success() {
  :
}

step_result_skipped() {
  :
}

step_result_soft_fail() {
  :
}

step_result_hard_fail() {
  :
}

init_output_styles() {
  :
}

init_logging() {
  :
}

write_log_only() {
  :
}

style_text() {
  :
}

emit_notice() {
  :
}

set_step_total() {
  :
}

announce_step() {
  :
}

announce_detail() {
  :
}

announce_warning() {
  :
}

announce_error() {
  :
}

announce_prompt() {
  :
}

print_summary_section() {
  :
}

print_summary_item() {
  :
}

close_step_block() {
  :
}

pipeline_reset() {
  :
}

pipeline_add_step() {
  :
}

pipeline_step_matches_mode() {
  :
}

pipeline_contains_step_id() {
  :
}

pipeline_count_steps_for_mode() {
  :
}

run_pipeline_steps() {
  :
}

register_step_definition() {
  :
}

step_definition_mode() {
  :
}

step_definition_title() {
  :
}

step_definition_function() {
  :
}

step_definition_count_flag() {
  :
}

append_registered_step() {
  :
}

append_runtime_component_steps() {
  :
}

append_runtime_install_pipeline() {
  :
}

define_runtime_pipeline() {
  :
}

define_bootstrap_pipeline() {
  :
}

bootstrap_missing_packages_present() {
  :
}

append_array_item() {
  :
}

package_is_installed() {
  :
}

run_with_terminal_stdin() {
  :
}

collect_missing_packages() {
  :
}

run_log_only() {
  :
}

run_interactive_log_only() {
  :
}

retry() {
  :
}

retry_log_only() {
  :
}

retry_interactive_log_only() {
  :
}

checkpoint_file() {
  :
}

has_checkpoint() {
  :
}

mark_checkpoint() {
  :
}

register_cleanup_path() {
  :
}

acquire_lock() {
  :
}

cleanup() {
  :
}

ensure_not_root() {
  :
}

require_command() {
  :
}

canonicalize_path() {
  :
}

require_exact_path() {
  :
}

validate_managed_paths() {
  :
}

get_host_name() {
  :
}

sanitize_label() {
  :
}

is_wayland_session() {
  :
}

is_hyprland_session() {
  :
}

is_supported_session() {
  :
}

ensure_supported_session() {
  :
}

ensure_arch() {
  :
}

github_ssh_expected() {
  :
}

github_ssh_force_reconcile() {
  :
}

ops_sudo_auth() {
  :
}

ops_pacman_upgrade_and_install_needed() {
  :
}

ops_pacman_upgrade_full() {
  :
}

ops_pacman_install_needed() {
  :
}

ops_pacman_remove_recursive() {
  :
}

ops_pacman_refresh_databases() {
  :
}

ops_backup_pacman_conf() {
  :
}

ops_enable_multilib_config() {
  :
}

ops_download_file() {
  :
}

ops_extract_tar_gz() {
  :
}

ops_build_yay_package() {
  :
}

ops_git_remote_add_origin() {
  :
}

ops_git_remote_set_origin() {
  :
}

ops_git_fetch_origin() {
  :
}

ops_git_checkout_main() {
  :
}

ops_git_checkout_main_from_origin() {
  :
}

ops_git_pull_main_ff_only() {
  :
}

ops_git_clone_main() {
  :
}

ops_gh_auth_login() {
  :
}

ops_gh_auth_refresh_admin_public_key() {
  :
}

ops_gh_delete_ssh_key() {
  :
}

ops_gh_create_ssh_key() {
  :
}

ops_npm_config_set_prefix() {
  :
}

ops_npm_install_codex_cli() {
  :
}

ops_ssh_regenerate_public_key() {
  :
}

ops_ssh_generate_key_pair() {
  :
}

ops_systemctl_user_daemon_reload() {
  :
}

ops_systemctl_user_start() {
  :
}

ops_aur_install_needed() {
  :
}

ensure_repo_origin_remote() {
  :
}

get_repo_branch() {
  :
}

current_repo_origin_status() {
  :
}

current_repo_commit_short() {
  :
}

config_init() {
  :
}

finalize_config() {
  :
}

execution_state_reset() {
  :
}

runtime_state_init() {
  :
}

record_soft_failure() {
  :
}

create_directories() {
  :
}

component_dispatch() {
  :
}

component_detect() {
  :
}

component_apply() {
  :
}

component_verify() {
  :
}

component_summary_status_text() {
  :
}

component_prepare_check_only_state() {
  :
}

setup_codex_cli() {
  :
}

codex_cli_shell_configured() {
  :
}

codex_cli_ready() {
  :
}

component_detect_codex_cli() {
  :
}

component_checkpoint_key_codex_cli() {
  :
}

component_apply_codex_cli() {
  :
}

component_verify_codex_cli() {
  :
}

detect_aur_helper() {
  :
}

component_detect_aur_helper() {
  :
}

component_checkpoint_key_aur_helper() {
  :
}

build_yay() {
  :
}

install_yay() {
  :
}

component_apply_aur_helper() {
  :
}

component_verify_aur_helper() {
  :
}

ensure_aur_helper() {
  :
}

desktop_integration_ready() {
  :
}

component_detect_desktop_integration() {
  :
}

component_checkpoint_key_desktop_integration() {
  :
}

component_apply_desktop_integration() {
  :
}

start_desktop_user_services() {
  :
}

component_verify_desktop_integration() {
  :
}

build_ssh_key_name() {
  :
}

current_public_ssh_key() {
  :
}

find_current_github_ssh_key() {
  :
}

github_has_expected_ssh_key_name() {
  :
}

github_ssh_ready() {
  :
}

component_detect_github_ssh() {
  :
}

component_checkpoint_key_github_ssh() {
  :
}

component_apply_github_ssh() {
  :
}

component_verify_github_ssh() {
  :
}

append_package() {
  :
}

load_package_file() {
  :
}

load_packages() {
  :
}

classify_package_origin() {
  :
}

target_packages_have_origin() {
  :
}

target_packages_have_official_entries() {
  :
}

target_packages_have_aur_entries() {
  :
}

collect_packages_by_origin() {
  :
}

report_requested_main_packages() {
  :
}

multilib_enabled() {
  :
}

ensure_multilib() {
  :
}

refresh_official_repo_index() {
  :
}

package_exists_in_official_repos() {
  :
}

install_official_packages_in_order() {
  :
}

install_aur_packages_in_order() {
  :
}

verify_command() {
  :
}

verify_package() {
  :
}

user_service_exists() {
  :
}

verify_user_service() {
  :
}

collect_version() {
  :
}

verify_installation() {
  :
}

attempt_final_repair_once() {
  :
}

ensure_final_verification_passed() {
  :
}

print_summary() {
  :
}

runtime_validate_environment_step() {
  :
}

update_system_step() {
  :
}

load_configuration_step() {
  :
}

check_only_step() {
  :
}

create_directories_step() {
  :
}

ensure_multilib_step() {
  :
}

prepare_aur_helper_step() {
  :
}

install_local_support_packages_step() {
  :
}

prepare_package_installation_step() {
  :
}

install_official_packages_step() {
  :
}

install_aur_packages_step() {
  :
}

finalize_package_installation_step() {
  :
}

codex_cli_step() {
  :
}

desktop_integration_step() {
  :
}

github_ssh_step() {
  :
}

final_verification_step() {
  :
}

handle_runtime_step_result_or_exit() {
  :
}

run_install() {
  :
}

runtime_state_reset() {
  :
}

state_reset_package_results() {
  :
}

state_reset_verification_results() {
  :
}

state_add_main_official_package() {
  :
}

state_add_main_aur_package() {
  :
}

state_add_official_failure() {
  :
}

state_add_aur_failure() {
  :
}

state_remove_array_item() {
  :
}

state_record_verification_item() {
  :
}

state_add_verified_item() {
  :
}

state_add_missing_item() {
  :
}

state_add_version_line() {
  :
}

state_add_soft_failure() {
  :
}

state_set_aur_helper() {
  :
}

state_get_aur_helper_name() {
  :
}

state_get_aur_helper_status() {
  :
}

state_set_temp_clipboard_package() {
  :
}

state_get_temp_clipboard_package() {
  :
}

state_official_repo_metadata_checked() {
  :
}

state_set_official_repo_metadata_checked() {
  :
}

state_official_repo_metadata_ready() {
  :
}

state_set_official_repo_metadata_ready() {
  :
}

state_has_package_failures() {
  :
}

state_has_missing_items() {
  :
}

state_has_verified_item() {
  :
}

state_get_verification_label() {
  :
}

state_get_verification_kind() {
  :
}

state_get_verification_repair_strategy() {
  :
}

state_get_verification_target() {
  :
}

component_outcome_changed_flag() {
  :
}

component_outcome_counts_as_ready() {
  :
}

component_outcome_step_status() {
  :
}

format_github_ssh_status() {
  :
}

format_desktop_integration_status() {
  :
}

ensure_temp_clipboard_utility() {
  :
}

cleanup_temp_clipboard_utility() {
  :
}

run_gh_auth_flow() {
  :
}

ensure_github_auth() {
  :
}

confirm_exclusive_github_ssh_key() {
  :
}

ensure_ssh_key() {
  :
}

remove_other_github_ssh_keys() {
  :
}

upload_ssh_key() {
  :
}

