#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$REPO_DIR/scripts/lib/shellcheck-runtime.sh"

# shellcheck disable=SC1091
source "$REPO_DIR/scripts/lib/module-manifest.sh"

SCAN_FILES=(
  "config/components.sh"
)

usage() {
  cat <<'EOF'
Uso:
  bash scripts/build-shellcheck-runtime.sh
  bash scripts/build-shellcheck-runtime.sh --check
EOF
}

append_unique() {
  local array_name="$1"
  local item="$2"
  local existing

  if should_skip_name "$item"; then
    return 0
  fi

  # shellcheck disable=SC2178
  declare -n target_array="$array_name"

  for existing in "${target_array[@]}"; do
    [[ "$existing" == "$item" ]] && return 0
  done

  target_array+=("$item")
}

should_skip_name() {
  case "$1" in
    BASHOPTS|BASHPID|BASH_ARGC|BASH_ARGV|BASH_ARGV0|BASH_COMMAND|BASH_LINENO|BASH_SOURCE|BASH_SUBSHELL|BASH_VERSINFO|DIRSTACK|EUID|FUNCNAME|GROUPS|IFS|OLDPWD|PATH|PIPESTATUS|PPID|PWD|SHELLOPTS|UID)
      return 0
      ;;
  esac

  return 1
}

register_scan_files() {
  local relative_path

  for relative_path in "${MODULE_RUNTIME_CHECK_FILES[@]}"; do
    [[ "$relative_path" == "scripts/lib/shellcheck-runtime.sh" ]] && continue
    append_unique SCAN_FILES "$relative_path"
  done
}

collect_variable_declarations() {
  local file_path="$1"

  awk '
    /^[[:space:]]*local[[:space:]]+/ {
      next
    }

    /^[[:space:]]*(readonly|declare)[[:space:]]+-[A-Za-z]+[[:space:]]+[A-Za-z_][A-Za-z0-9_]*=/ {
      line = $0
      sub(/^[[:space:]]+/, "", line)
      split(line, fields, /[[:space:]]+/)
      flags = fields[2]
      split(fields[3], parts, "=")
      name = parts[1]
      kind = "scalar"
      if (flags ~ /A/) {
        kind = "assoc"
      } else if (flags ~ /a/) {
        kind = "array"
      }
      print kind "|" name
      next
    }

    /^[[:space:]]*export[[:space:]]+[A-Za-z_][A-Za-z0-9_]*=/ {
      line = $0
      sub(/^[[:space:]]*export[[:space:]]+/, "", line)
      split(line, parts, "=")
      name = parts[1]
      print "scalar|" name
      next
    }

    /^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*=/ {
      line = $0
      sub(/^[[:space:]]+/, "", line)
      split(line, parts, "=")
      name = parts[1]
      kind = "scalar"
      if (line ~ /^[A-Za-z_][A-Za-z0-9_]*=\(/) {
        kind = "array"
      }
      print kind "|" name
    }
  ' "$file_path"
}

collect_function_names() {
  local file_path="$1"

  awk '
    /^[A-Za-z_][A-Za-z0-9_]*\(\)[[:space:]]*\{/ {
      split($1, parts, "(")
      print parts[1]
    }
  ' "$file_path"
}

generate_shellcheck_runtime() {
  local relative_path
  local file_path
  local declaration
  local declaration_kind
  local declaration_name
  local function_name

  local scalar_vars=()
  local array_vars=()
  local assoc_vars=()
  local function_names=()

  register_scan_files

  for relative_path in "${SCAN_FILES[@]}"; do
    file_path="$REPO_DIR/$relative_path"

    while IFS= read -r declaration; do
      [[ -n "$declaration" ]] || continue
      declaration_kind="${declaration%%|*}"
      declaration_name="${declaration#*|}"

      case "$declaration_kind" in
        scalar)
          append_unique scalar_vars "$declaration_name"
          ;;
        array)
          append_unique array_vars "$declaration_name"
          ;;
        assoc)
          append_unique assoc_vars "$declaration_name"
          ;;
      esac
    done < <(collect_variable_declarations "$file_path")

    while IFS= read -r function_name; do
      [[ -n "$function_name" ]] || continue
      append_unique function_names "$function_name"
    done < <(collect_function_names "$file_path")
  done

  cat <<'EOF'
#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC2034
# This file is generated by `bash scripts/build-shellcheck-runtime.sh`.
# Do not edit it directly.

EOF

  if ((${#scalar_vars[@]} > 0)); then
    for declaration_name in "${scalar_vars[@]}"; do
      if should_skip_name "$declaration_name"; then
        continue
      fi
      printf '%s=""\n' "$declaration_name"
    done
    printf '\n'
  fi

  if ((${#array_vars[@]} > 0)); then
    for declaration_name in "${array_vars[@]}"; do
      if should_skip_name "$declaration_name"; then
        continue
      fi
      printf '%s=()\n' "$declaration_name"
    done
    printf '\n'
  fi

  if ((${#assoc_vars[@]} > 0)); then
    for declaration_name in "${assoc_vars[@]}"; do
      if should_skip_name "$declaration_name"; then
        continue
      fi
      printf 'declare -Ag %s=()\n' "$declaration_name"
    done
    printf '\n'
  fi

  for function_name in "${function_names[@]}"; do
    printf '%s() {\n' "$function_name"
    printf '  :\n'
    printf '}\n\n'
  done
}

write_or_check_shellcheck_runtime() {
  local temp_file

  temp_file="$(mktemp)"
  generate_shellcheck_runtime >"$temp_file"

  if [[ "${1:-}" == "--check" ]]; then
    if ! cmp -s "$OUTPUT_FILE" "$temp_file"; then
      printf 'Erro: scripts/lib/shellcheck-runtime.sh está desatualizado. Rode bash scripts/build-shellcheck-runtime.sh.\n' >&2
      rm -f "$temp_file"
      exit 1
    fi
    rm -f "$temp_file"
    return 0
  fi

  mv "$temp_file" "$OUTPUT_FILE"
}

main() {
  case "${1:-}" in
    ""|--check)
      write_or_check_shellcheck_runtime "${1:-}"
      ;;
    -h|--help)
      usage
      ;;
    *)
      printf 'Erro: opção desconhecida: %s\n' "${1:-}" >&2
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
