#!/usr/bin/env bash
# shellcheck shell=bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$REPO_DIR/install.sh"

FRAGMENTS=(
  "$REPO_DIR/scripts/lib/cli.sh"
  "$REPO_DIR/scripts/bootstrap/step-result.sh"
  "$REPO_DIR/scripts/bootstrap/ui.sh"
  "$REPO_DIR/scripts/bootstrap/process.sh"
  "$REPO_DIR/scripts/bootstrap/locking.sh"
  "$REPO_DIR/scripts/bootstrap/env.sh"
  "$REPO_DIR/scripts/bootstrap/repo.sh"
  "$REPO_DIR/scripts/bootstrap/entrypoint.sh"
)

usage() {
  cat <<'EOF'
Uso:
  bash scripts/build-bootstrap.sh
  bash scripts/build-bootstrap.sh --check
EOF
}

append_fragment() {
  local fragment_path="$1"
  local fragment_label="${fragment_path#"$REPO_DIR"/}"

  printf '\n# --- begin: %s ---\n' "$fragment_label"
  awk 'NR == 1 && /^#!\/usr\/bin\/env bash$/ { next } { print }' "$fragment_path"
  printf '# --- end: %s ---\n' "$fragment_label"
}

generate_bootstrap() {
  local fragment_path

  cat <<'EOF'
#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC2034
# This file is generated by `bash scripts/build-bootstrap.sh`.
# Do not edit it directly.

set -euo pipefail
EOF

  for fragment_path in "${FRAGMENTS[@]}"; do
    append_fragment "$fragment_path"
  done
}

write_or_check_bootstrap() {
  local temp_file

  temp_file="$(mktemp)"
  generate_bootstrap >"$temp_file"

  if [[ "${1:-}" == "--check" ]]; then
    if ! cmp -s "$OUTPUT_FILE" "$temp_file"; then
      printf 'Erro: install.sh está desatualizado. Rode bash scripts/build-bootstrap.sh.\n' >&2
      rm -f "$temp_file"
      exit 1
    fi
    rm -f "$temp_file"
    return 0
  fi

  mv "$temp_file" "$OUTPUT_FILE"
  chmod +x "$OUTPUT_FILE"
}

main() {
  case "${1:-}" in
    ""|--check)
      write_or_check_bootstrap "${1:-}"
      ;;
    -h|--help)
      usage
      ;;
    *)
      printf 'Erro: opção desconhecida: %s\n' "${1:-}" >&2
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
